FROM golang:1.21

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify
RUN go install github.com/cosmtrek/air@latest

COPY . .
RUN go build -o /go/bin/app

EXPOSE 8080

ENTRYPOINT ["air"]